import { useState, useRef, useEffect } from 'react';
// ExamLogin is intentionally unused — direct login is disabled.
// Access is only via JWT invite links generated by the admin panel.
// import { ExamLogin } from './components/ExamLogin';
import { ExamInterface } from './components/ExamInterface';
import { ResultScreen } from './components/ResultScreen';
import { FullscreenManager } from './components/FullscreenManager';
import { ViolationModal } from './components/ViolationModal';
import { ExamData, Answer } from './types/exam';
import { calculateScore, loadExamData } from './utils/examUtils';
import { BACKEND_URL } from './config';

type AppState = 'login' | 'exam' | 'result';

const generateSessionKey = (name: string, examCode: string): string => {
  const ts = Date.now();
  const safeName = name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
  return `${safeName}_${examCode}_${ts}`;
};

const resolveGrade = (examData: ExamData, score: number, totalMarks: number): string => {
  if (!examData.grading || examData.grading.length === 0) return '';
  const pct = totalMarks > 0 ? (score / totalMarks) * 100 : 0;
  const match = [...examData.grading]
    .sort((a, b) => b.minPercentage - a.minPercentage)
    .find((g) => pct >= g.minPercentage);
  return match ? match.grade : 'F';
};

/** Decode the payload part of a JWT without verifying the signature. */
const decodeJwtPayload = (token: string): Record<string, any> | null => {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) return null;
    const b64 = parts[1].replace(/-/g, '+').replace(/_/g, '/');
    const json = decodeURIComponent(
      atob(b64).split('').map(c => '%' + c.charCodeAt(0).toString(16).padStart(2, '0')).join('')
    );
    return JSON.parse(json);
  } catch {
    return null;
  }
};

const CAREERS_URL = 'https://www.azalio.io/careers/';
const REDIRECT_SECONDS = 10;

function CareersRedirectPage() {
  const [countdown, setCountdown] = useState(REDIRECT_SECONDS);

  useEffect(() => {
    const timer = setInterval(() => {
      setCountdown(prev => {
        if (prev <= 1) {
          clearInterval(timer);
          window.location.href = CAREERS_URL;
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-800 to-slate-900 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl p-10 max-w-md w-full text-center">
        {/* Logo / icon */}
        <div className="w-16 h-16 bg-blue-50 rounded-2xl flex items-center justify-center mx-auto mb-6">
          <svg className="w-9 h-9 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8}
              d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
          </svg>
        </div>

        <h1 className="text-2xl font-bold text-gray-800 mb-2">Looking for a Job?</h1>
        <p className="text-gray-500 text-sm leading-relaxed mb-6">
          This page is only accessible via a personalised invite link sent by our team.
          To apply for open positions at Azalio, please visit our careers page.
        </p>

        {/* Countdown ring */}
        <div className="flex flex-col items-center gap-2 mb-6">
          <div className="w-14 h-14 rounded-full border-4 border-blue-100 flex items-center justify-center">
            <span className="text-xl font-bold text-blue-600">{countdown}</span>
          </div>
          <p className="text-xs text-gray-400">Redirecting in {countdown} second{countdown !== 1 ? 's' : ''}…</p>
        </div>

        <a
          href={CAREERS_URL}
          className="block w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-xl transition text-sm"
        >
          Go to Careers Page Now
        </a>
      </div>
    </div>
  );
}

function App() {
  const [state, setState]                 = useState<AppState>('login');
  const [examData, setExamData]           = useState<ExamData | null>(null);
  const [studentName, setStudentName]     = useState('');
  const [studentEmail, setStudentEmail]   = useState('');
  const [jwtJti, setJwtJti]               = useState('');
  const [sessionKey, setSessionKey]       = useState('');
  const [violations, setViolations]       = useState(0);
  const [examPhase, setExamPhase]         = useState<'setup' | 'disclaimer' | 'active'>('setup');
  const [examStartTime, setExamStartTime] = useState<string | null>(null);
  const [isJwtMode, setIsJwtMode]         = useState(false);
  const [jwtError, setJwtError]           = useState('');
  const [showViolationModal, setShowViolationModal] = useState(false);
  const [pendingSubmitAnswers, setPendingSubmitAnswers] = useState<Answer[]>([]);
  const [pendingOrderMap, setPendingOrderMap]           = useState<Record<string, number>>({});
  const [resultData, setResultData] = useState<{
    score: number; totalMarks: number; details: any[];
  } | null>(null);

  const suppressUntil = useRef<number>(0);

  // ── JWT invite-link detection ───────────────────────────────────────────────
  const LS_KEY = 'qs_exam_token';

  const startExamFromToken = (token: string) => {
    const payload = decodeJwtPayload(token);
    if (!payload) { setJwtError('Invalid invite link.'); return; }

    // Expired → immediate redirect, no waiting
    if (payload.exp && Date.now() / 1000 > payload.exp) {
      localStorage.removeItem(LS_KEY);
      window.location.href = 'https://www.azalio.io/';
      return;
    }

    const { jti, sub: email, name, examCode } = payload;
    if (!examCode) { setJwtError('Invalid invite link: missing exam code.'); return; }

    // Check if already submitted
    fetch(`${BACKEND_URL}/api/exam/check-token/${jti}`)
      .then(r => r.json())
      .then(data => {
        if (data.used) {
          localStorage.removeItem(LS_KEY);
          setJwtError('This invite link has already been used. Please contact your administrator for a new link.');
          return;
        }
        return loadExamData(examCode);
      })
      .then(data => {
        if (!data) return;
        if ((data as any).used !== undefined) return; // guard against check-token response leaking here

        const examDataObj = data as ExamData;
        setStudentName(name ?? '');
        setStudentEmail(email ?? '');
        setJwtJti(jti ?? '');
        setExamData(examDataObj);
        setSessionKey(generateSessionKey(name ?? 'candidate', examCode));
        setViolations(0);
        setExamStartTime(new Date().toISOString());
        setIsJwtMode(true);
        setState('exam');
      })
      .catch(() => setJwtError('Failed to load exam. Please try again.'));
  };

  useEffect(() => {
    const params   = new URLSearchParams(window.location.search);
    const urlToken = params.get('usr');

    if (urlToken) {
      // New token from URL → always overwrite localStorage then clean URL
      localStorage.setItem(LS_KEY, urlToken);
      window.history.replaceState({}, '', window.location.pathname);
      startExamFromToken(urlToken);
      return;
    }

    // No URL token → try stored token (e.g. page refresh mid-exam)
    const stored = localStorage.getItem(LS_KEY);
    if (stored) {
      const payload = decodeJwtPayload(stored);
      if (!payload || (payload.exp && Date.now() / 1000 > payload.exp)) {
        // Stored token is expired → clear and redirect immediately
        localStorage.removeItem(LS_KEY);
        window.location.href = 'https://www.azalio.io/';
        return;
      }
      startExamFromToken(stored);
    }
    // No token at all → falls through to CareersRedirectPage
  }, []);

  // ── Normal login flow ───────────────────────────────────────────────────────
  const handleExamStart = (data: ExamData, name: string) => {
    setExamData(data);
    setStudentName(name);
    setStudentEmail('');
    setJwtJti('');
    setSessionKey(generateSessionKey(name, data.examCode));
    setState('exam');
    setViolations(0);
    const needsRecording = !!(data.recording?.camera || data.recording?.screen);
    setExamPhase(needsRecording ? 'setup' : 'disclaimer');
    setExamStartTime(new Date().toISOString());
  };

  const handleViolation = () => {
    if (Date.now() < suppressUntil.current) return;
    setViolations((v) => {
      const newCount = v + 1;
      const maxV = examData?.maxViolations ?? 3;
      if (newCount >= maxV) {
        // Show custom modal instead of alert — exam will submit when user acknowledges
        setPendingSubmitAnswers([]);
        setPendingOrderMap({});
        setShowViolationModal(true);
      }
      return newCount;
    });
  };

  const handleViolationAcknowledge = () => {
    setShowViolationModal(false);
    doSubmit(pendingSubmitAnswers, pendingOrderMap);
  };

  const handleSuppressViolations = (ms: number) => {
    suppressUntil.current = Date.now() + ms;
  };

  const handleExamSubmit = (answers: Answer[], questionOrderMap: Record<string, number> = {}) => {
    doSubmit(answers, questionOrderMap);
  };

  const doSubmit = (answers: Answer[], questionOrderMap: Record<string, number>) => {
    if (!examData) return;
    const result = calculateScore(examData, answers, questionOrderMap);
    setResultData(result);
    setState('result');
    if (document.fullscreenElement) document.exitFullscreen();
    localStorage.removeItem('qs_exam_token'); // token consumed on submit
    persistResult(examData, result.score, result.totalMarks, result.details);
  };

  const persistResult = (data: ExamData, score: number, totalMarks: number, details: any[]) => {
    const grade = resolveGrade(data, score, totalMarks);
    const payload = {
      sessionKey,
      studentName,
      studentEmail: studentEmail || undefined,
      jti: jwtJti || undefined,
      examCode: data.examCode,
      examTitle: data.examTitle,
      score,
      totalMarks,
      grade: grade || null,
      details,
      startedAt: examStartTime,
    };
    fetch(`${BACKEND_URL}/api/result/save`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    }).catch((err) => console.error('[exam] Failed to persist result:', err));
  };

  const handleRestart = () => {
    setState('login');
    setExamData(null);
    setStudentName('');
    setStudentEmail('');
    setJwtJti('');
    setSessionKey('');
    setViolations(0);
    setExamPhase('setup');
    setResultData(null);
    setExamStartTime(null);
    setIsJwtMode(false);
    setJwtError('');
    setShowViolationModal(false);
  };

  // ── JWT error screen ────────────────────────────────────────────────────────
  if (jwtError) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-800 to-slate-900 flex items-center justify-center p-4">
        <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-sm w-full text-center">
          <div className="w-14 h-14 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg className="w-7 h-7 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M12 9v2m0 4h.01M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
            </svg>
          </div>
          <h2 className="text-lg font-bold text-gray-800 mb-2">Cannot Start Exam</h2>
          <p className="text-sm text-gray-500 mb-6">{jwtError}</p>
          <button
            onClick={() => setJwtError('')}
            className="w-full bg-slate-800 text-white py-2.5 rounded-lg text-sm font-semibold hover:bg-slate-900 transition"
          >
            Go to Login
          </button>
        </div>
      </div>
    );
  }

  return (
    <FullscreenManager examActive={state === 'exam' && examPhase === 'active'} onViolation={handleViolation}>
      {state === 'login' && <CareersRedirectPage />}

      {state === 'exam' && examData && (
        <ExamInterface
          examData={examData}
          studentName={studentName}
          studentEmail={studentEmail}
          sessionKey={sessionKey}
          isJwtMode={isJwtMode}
          onSubmit={handleExamSubmit}
          onSuppressViolations={handleSuppressViolations}
          onPhaseActive={() => setExamPhase('active')}
          onViolation={handleViolation}
          violations={violations}
        />
      )}

      {state === 'result' && examData && resultData && (
        <ResultScreen
          examData={examData}
          studentName={studentName}
          score={resultData.score}
          totalMarks={resultData.totalMarks}
          details={resultData.details}
          onRestart={handleRestart}
        />
      )}

      {/* Violation auto-submit modal — shown on top of everything */}
      {showViolationModal && examData && (
        <ViolationModal
          violations={examData.maxViolations ?? 3}
          maxViolations={examData.maxViolations ?? 3}
          onAcknowledge={handleViolationAcknowledge}
        />
      )}
    </FullscreenManager>
  );
}

export default App;
